export const CHART_CURRENT_TIME = 'chart/CHART_CURRENT_TIME';
export const CHART_CURRENT_TIME_INCREMENT = 'chart/CHART_CURRENT_TIME_INCREMENT';
export const CHART_CURRENT_TIME_DECREMENT = 'chart/CHART_CURRENT_TIME_DECREMENT';
export const CHART_TOOLTIP_TIME = 'chart/CHART_TOOLTIP_TIME';
export const MAP_TOOLTIP_STATION = 'chart/MAP_TOOLTIP_STATION';
