export const CHART_CURRENT_TIME = 'ui/CHART_CURRENT_TIME';
export const CHART_TOOLTIP_TIME = 'ui/CHART_TOOLTIP_TIME';
export const MAP_TOOLTIP_STATION = 'ui/MAP_TOOLTIP_STATION';
export const GRID_SELECTED_ROWS = 'ui/GRID_SELECTED_ROWS';
